// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api_catalog.proto

package api_catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_REST                 Protocol = 1
	Protocol_WS                   Protocol = 2
	Protocol_GRPC                 Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "REST",
		2: "WS",
		3: "GRPC",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"REST":                 1,
		"WS":                   2,
		"GRPC":                 3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_catalog_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_catalog_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{0}
}

type Source int32

const (
	Source_SOURCE_UNSPECIFIED Source = 0
	Source_ENV                Source = 1
	Source_MANUAL             Source = 2
	Source_SCAN               Source = 3
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "ENV",
		2: "MANUAL",
		3: "SCAN",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"ENV":                1,
		"MANUAL":             2,
		"SCAN":               3,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_api_catalog_proto_enumTypes[1].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_api_catalog_proto_enumTypes[1]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_ACTIVE             Status = 1
	Status_DEPRECATED         Status = 2
	Status_DOWN               Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "DEPRECATED",
		3: "DOWN",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"DEPRECATED":         2,
		"DOWN":               3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_catalog_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_catalog_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{2}
}

type AuthPolicy int32

const (
	AuthPolicy_AUTH_POLICY_UNSPECIFIED AuthPolicy = 0
	AuthPolicy_PUBLIC                  AuthPolicy = 1
	AuthPolicy_BEARER                  AuthPolicy = 2
	AuthPolicy_ADMIN_KEY               AuthPolicy = 3
)

// Enum value maps for AuthPolicy.
var (
	AuthPolicy_name = map[int32]string{
		0: "AUTH_POLICY_UNSPECIFIED",
		1: "PUBLIC",
		2: "BEARER",
		3: "ADMIN_KEY",
	}
	AuthPolicy_value = map[string]int32{
		"AUTH_POLICY_UNSPECIFIED": 0,
		"PUBLIC":                  1,
		"BEARER":                  2,
		"ADMIN_KEY":               3,
	}
)

func (x AuthPolicy) Enum() *AuthPolicy {
	p := new(AuthPolicy)
	*p = x
	return p
}

func (x AuthPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_catalog_proto_enumTypes[3].Descriptor()
}

func (AuthPolicy) Type() protoreflect.EnumType {
	return &file_api_catalog_proto_enumTypes[3]
}

func (x AuthPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthPolicy.Descriptor instead.
func (AuthPolicy) EnumDescriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{3}
}

type Service struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl              string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Protocols            []Protocol             `protobuf:"varint,4,rep,packed,name=protocols,proto3,enum=api_catalog.Protocol" json:"protocols,omitempty"`
	Source               Source                 `protobuf:"varint,5,opt,name=source,proto3,enum=api_catalog.Source" json:"source,omitempty"`
	Status               Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=api_catalog.Status" json:"status,omitempty"`
	Description          string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Tags                 []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	ApiInfoUrl           string                 `protobuf:"bytes,10,opt,name=api_info_url,json=apiInfoUrl,proto3" json:"api_info_url,omitempty"`
	GrpcAddress          string                 `protobuf:"bytes,11,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	LastScannedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_scanned_at,json=lastScannedAt,proto3" json:"last_scanned_at,omitempty"`
	LastScanOk           bool                   `protobuf:"varint,13,opt,name=last_scan_ok,json=lastScanOk,proto3" json:"last_scan_ok,omitempty"`
	LastScanError        string                 `protobuf:"bytes,14,opt,name=last_scan_error,json=lastScanError,proto3" json:"last_scan_error,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AuthPolicy           AuthPolicy             `protobuf:"varint,17,opt,name=auth_policy,json=authPolicy,proto3,enum=api_catalog.AuthPolicy" json:"auth_policy,omitempty"`
	PublicPaths          []string               `protobuf:"bytes,18,rep,name=public_paths,json=publicPaths,proto3" json:"public_paths,omitempty"`
	HasEndpointOverrides bool                   `protobuf:"varint,19,opt,name=has_endpoint_overrides,json=hasEndpointOverrides,proto3" json:"has_endpoint_overrides,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Service) GetProtocols() []Protocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Service) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *Service) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetApiInfoUrl() string {
	if x != nil {
		return x.ApiInfoUrl
	}
	return ""
}

func (x *Service) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *Service) GetLastScannedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastScannedAt
	}
	return nil
}

func (x *Service) GetLastScanOk() bool {
	if x != nil {
		return x.LastScanOk
	}
	return false
}

func (x *Service) GetLastScanError() string {
	if x != nil {
		return x.LastScanError
	}
	return ""
}

func (x *Service) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Service) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Service) GetAuthPolicy() AuthPolicy {
	if x != nil {
		return x.AuthPolicy
	}
	return AuthPolicy_AUTH_POLICY_UNSPECIFIED
}

func (x *Service) GetPublicPaths() []string {
	if x != nil {
		return x.PublicPaths
	}
	return nil
}

func (x *Service) GetHasEndpointOverrides() bool {
	if x != nil {
		return x.HasEndpointOverrides
	}
	return false
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Protocol      Protocol               `protobuf:"varint,3,opt,name=protocol,proto3,enum=api_catalog.Protocol" json:"protocol,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	OperationId   string                 `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Deprecated    bool                   `protobuf:"varint,9,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	AuthPolicy    *AuthPolicy            `protobuf:"varint,10,opt,name=auth_policy,json=authPolicy,proto3,enum=api_catalog.AuthPolicy,oneof" json:"auth_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Endpoint) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Endpoint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Endpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Endpoint) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Endpoint) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Endpoint) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Endpoint) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Endpoint) GetAuthPolicy() AuthPolicy {
	if x != nil && x.AuthPolicy != nil {
		return *x.AuthPolicy
	}
	return AuthPolicy_AUTH_POLICY_UNSPECIFIED
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_api_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListServicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListServicesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Service             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_api_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesResponse) GetItems() []*Service {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListServicesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_api_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=api_catalog.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_api_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListEndpointsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListEndpointsRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Endpoint            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_api_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListEndpointsResponse) GetItems() []*Endpoint {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Protocols     []Protocol             `protobuf:"varint,3,rep,packed,name=protocols,proto3,enum=api_catalog.Protocol" json:"protocols,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ApiInfoUrl    string                 `protobuf:"bytes,7,opt,name=api_info_url,json=apiInfoUrl,proto3" json:"api_info_url,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,8,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	AuthPolicy    AuthPolicy             `protobuf:"varint,10,opt,name=auth_policy,json=authPolicy,proto3,enum=api_catalog.AuthPolicy" json:"auth_policy,omitempty"`
	PublicPaths   []string               `protobuf:"bytes,11,rep,name=public_paths,json=publicPaths,proto3" json:"public_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_api_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateServiceRequest) GetProtocols() []Protocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *CreateServiceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateServiceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateServiceRequest) GetApiInfoUrl() string {
	if x != nil {
		return x.ApiInfoUrl
	}
	return ""
}

func (x *CreateServiceRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *CreateServiceRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateServiceRequest) GetAuthPolicy() AuthPolicy {
	if x != nil {
		return x.AuthPolicy
	}
	return AuthPolicy_AUTH_POLICY_UNSPECIFIED
}

func (x *CreateServiceRequest) GetPublicPaths() []string {
	if x != nil {
		return x.PublicPaths
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Owner         *string                `protobuf:"bytes,3,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        *Status                `protobuf:"varint,5,opt,name=status,proto3,enum=api_catalog.Status,oneof" json:"status,omitempty"`
	AuthPolicy    *AuthPolicy            `protobuf:"varint,6,opt,name=auth_policy,json=authPolicy,proto3,enum=api_catalog.AuthPolicy,oneof" json:"auth_policy,omitempty"`
	PublicPaths   []string               `protobuf:"bytes,7,rep,name=public_paths,json=publicPaths,proto3" json:"public_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_api_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServiceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateServiceRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *UpdateServiceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateServiceRequest) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *UpdateServiceRequest) GetAuthPolicy() AuthPolicy {
	if x != nil && x.AuthPolicy != nil {
		return *x.AuthPolicy
	}
	return AuthPolicy_AUTH_POLICY_UNSPECIFIED
}

func (x *UpdateServiceRequest) GetPublicPaths() []string {
	if x != nil {
		return x.PublicPaths
	}
	return nil
}

type UpdateEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthPolicy    *AuthPolicy            `protobuf:"varint,2,opt,name=auth_policy,json=authPolicy,proto3,enum=api_catalog.AuthPolicy,oneof" json:"auth_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEndpointRequest) Reset() {
	*x = UpdateEndpointRequest{}
	mi := &file_api_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointRequest) ProtoMessage() {}

func (x *UpdateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointRequest.ProtoReflect.Descriptor instead.
func (*UpdateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEndpointRequest) GetAuthPolicy() AuthPolicy {
	if x != nil && x.AuthPolicy != nil {
		return *x.AuthPolicy
	}
	return AuthPolicy_AUTH_POLICY_UNSPECIFIED
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_api_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_api_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteServiceResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RescanAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanAllRequest) Reset() {
	*x = RescanAllRequest{}
	mi := &file_api_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanAllRequest) ProtoMessage() {}

func (x *RescanAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanAllRequest.ProtoReflect.Descriptor instead.
func (*RescanAllRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *RescanAllRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RescanServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanServiceRequest) Reset() {
	*x = RescanServiceRequest{}
	mi := &file_api_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanServiceRequest) ProtoMessage() {}

func (x *RescanServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanServiceRequest.ProtoReflect.Descriptor instead.
func (*RescanServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *RescanServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RescanReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServicesScanned int32                  `protobuf:"varint,1,opt,name=services_scanned,json=servicesScanned,proto3" json:"services_scanned,omitempty"`
	ServicesOk      int32                  `protobuf:"varint,2,opt,name=services_ok,json=servicesOk,proto3" json:"services_ok,omitempty"`
	ServicesFailed  int32                  `protobuf:"varint,3,opt,name=services_failed,json=servicesFailed,proto3" json:"services_failed,omitempty"`
	Errors          []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RescanReport) Reset() {
	*x = RescanReport{}
	mi := &file_api_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanReport) ProtoMessage() {}

func (x *RescanReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanReport.ProtoReflect.Descriptor instead.
func (*RescanReport) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *RescanReport) GetServicesScanned() int32 {
	if x != nil {
		return x.ServicesScanned
	}
	return 0
}

func (x *RescanReport) GetServicesOk() int32 {
	if x != nil {
		return x.ServicesOk
	}
	return 0
}

func (x *RescanReport) GetServicesFailed() int32 {
	if x != nil {
		return x.ServicesFailed
	}
	return 0
}

func (x *RescanReport) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *RescanReport) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_api_catalog_proto protoreflect.FileDescriptor

const file_api_catalog_proto_rawDesc = "" +
	"\n" +
	"\x11api_catalog.proto\x12\vapi_catalog\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x05\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x123\n" +
	"\tprotocols\x18\x04 \x03(\x0e2\x15.api_catalog.ProtocolR\tprotocols\x12+\n" +
	"\x06source\x18\x05 \x01(\x0e2\x13.api_catalog.SourceR\x06source\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.api_catalog.StatusR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12 \n" +
	"\fapi_info_url\x18\n" +
	" \x01(\tR\n" +
	"apiInfoUrl\x12!\n" +
	"\fgrpc_address\x18\v \x01(\tR\vgrpcAddress\x12B\n" +
	"\x0flast_scanned_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rlastScannedAt\x12 \n" +
	"\flast_scan_ok\x18\r \x01(\bR\n" +
	"lastScanOk\x12&\n" +
	"\x0flast_scan_error\x18\x0e \x01(\tR\rlastScanError\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\vauth_policy\x18\x11 \x01(\x0e2\x17.api_catalog.AuthPolicyR\n" +
	"authPolicy\x12!\n" +
	"\fpublic_paths\x18\x12 \x03(\tR\vpublicPaths\x124\n" +
	"\x16has_endpoint_overrides\x18\x13 \x01(\bR\x14hasEndpointOverrides\"\xd8\x02\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x121\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x15.api_catalog.ProtocolR\bprotocol\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12!\n" +
	"\foperation_id\x18\a \x01(\tR\voperationId\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"deprecated\x18\t \x01(\bR\n" +
	"deprecated\x12=\n" +
	"\vauth_policy\x18\n" +
	" \x01(\x0e2\x17.api_catalog.AuthPolicyH\x00R\n" +
	"authPolicy\x88\x01\x01B\x0e\n" +
	"\f_auth_policy\"[\n" +
	"\x13ListServicesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"X\n" +
	"\x14ListServicesResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.api_catalog.ServiceR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"#\n" +
	"\x11GetServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x14ListEndpointsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x121\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x15.api_catalog.ProtocolR\bprotocol\"D\n" +
	"\x15ListEndpointsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.api_catalog.EndpointR\x05items\"\x87\x03\n" +
	"\x14CreateServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x123\n" +
	"\tprotocols\x18\x03 \x03(\x0e2\x15.api_catalog.ProtocolR\tprotocols\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12 \n" +
	"\fapi_info_url\x18\a \x01(\tR\n" +
	"apiInfoUrl\x12!\n" +
	"\fgrpc_address\x18\b \x01(\tR\vgrpcAddress\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x128\n" +
	"\vauth_policy\x18\n" +
	" \x01(\x0e2\x17.api_catalog.AuthPolicyR\n" +
	"authPolicy\x12!\n" +
	"\fpublic_paths\x18\v \x03(\tR\vpublicPaths\"\xc5\x02\n" +
	"\x14UpdateServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05owner\x18\x03 \x01(\tH\x01R\x05owner\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.api_catalog.StatusH\x02R\x06status\x88\x01\x01\x12=\n" +
	"\vauth_policy\x18\x06 \x01(\x0e2\x17.api_catalog.AuthPolicyH\x03R\n" +
	"authPolicy\x88\x01\x01\x12!\n" +
	"\fpublic_paths\x18\a \x03(\tR\vpublicPathsB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_ownerB\t\n" +
	"\a_statusB\x0e\n" +
	"\f_auth_policy\"v\n" +
	"\x15UpdateEndpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\vauth_policy\x18\x02 \x01(\x0e2\x17.api_catalog.AuthPolicyH\x00R\n" +
	"authPolicy\x88\x01\x01B\x0e\n" +
	"\f_auth_policy\"&\n" +
	"\x14DeleteServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteServiceResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"(\n" +
	"\x10RescanAllRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"&\n" +
	"\x14RescanServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd8\x01\n" +
	"\fRescanReport\x12)\n" +
	"\x10services_scanned\x18\x01 \x01(\x05R\x0fservicesScanned\x12\x1f\n" +
	"\vservices_ok\x18\x02 \x01(\x05R\n" +
	"servicesOk\x12'\n" +
	"\x0fservices_failed\x18\x03 \x01(\x05R\x0eservicesFailed\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt*@\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04REST\x10\x01\x12\x06\n" +
	"\x02WS\x10\x02\x12\b\n" +
	"\x04GRPC\x10\x03*?\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ENV\x10\x01\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x02\x12\b\n" +
	"\x04SCAN\x10\x03*F\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\x0e\n" +
	"\n" +
	"DEPRECATED\x10\x02\x12\b\n" +
	"\x04DOWN\x10\x03*P\n" +
	"\n" +
	"AuthPolicy\x12\x1b\n" +
	"\x17AUTH_POLICY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\n" +
	"\n" +
	"\x06BEARER\x10\x02\x12\r\n" +
	"\tADMIN_KEY\x10\x032\xcc\x05\n" +
	"\n" +
	"ApiCatalog\x12S\n" +
	"\fListServices\x12 .api_catalog.ListServicesRequest\x1a!.api_catalog.ListServicesResponse\x12B\n" +
	"\n" +
	"GetService\x12\x1e.api_catalog.GetServiceRequest\x1a\x14.api_catalog.Service\x12V\n" +
	"\rListEndpoints\x12!.api_catalog.ListEndpointsRequest\x1a\".api_catalog.ListEndpointsResponse\x12H\n" +
	"\rCreateService\x12!.api_catalog.CreateServiceRequest\x1a\x14.api_catalog.Service\x12H\n" +
	"\rUpdateService\x12!.api_catalog.UpdateServiceRequest\x1a\x14.api_catalog.Service\x12V\n" +
	"\rDeleteService\x12!.api_catalog.DeleteServiceRequest\x1a\".api_catalog.DeleteServiceResponse\x12K\n" +
	"\x0eUpdateEndpoint\x12\".api_catalog.UpdateEndpointRequest\x1a\x15.api_catalog.Endpoint\x12E\n" +
	"\tRescanAll\x12\x1d.api_catalog.RescanAllRequest\x1a\x19.api_catalog.RescanReport\x12M\n" +
	"\rRescanService\x12!.api_catalog.RescanServiceRequest\x1a\x19.api_catalog.RescanReportB Z\x1erag-hp/api_catalog;api_catalogb\x06proto3"

var (
	file_api_catalog_proto_rawDescOnce sync.Once
	file_api_catalog_proto_rawDescData []byte
)

func file_api_catalog_proto_rawDescGZIP() []byte {
	file_api_catalog_proto_rawDescOnce.Do(func() {
		file_api_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_catalog_proto_rawDesc), len(file_api_catalog_proto_rawDesc)))
	})
	return file_api_catalog_proto_rawDescData
}

var file_api_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_catalog_proto_goTypes = []any{
	(Protocol)(0),                 // 0: api_catalog.Protocol
	(Source)(0),                   // 1: api_catalog.Source
	(Status)(0),                   // 2: api_catalog.Status
	(AuthPolicy)(0),               // 3: api_catalog.AuthPolicy
	(*Service)(nil),               // 4: api_catalog.Service
	(*Endpoint)(nil),              // 5: api_catalog.Endpoint
	(*ListServicesRequest)(nil),   // 6: api_catalog.ListServicesRequest
	(*ListServicesResponse)(nil),  // 7: api_catalog.ListServicesResponse
	(*GetServiceRequest)(nil),     // 8: api_catalog.GetServiceRequest
	(*ListEndpointsRequest)(nil),  // 9: api_catalog.ListEndpointsRequest
	(*ListEndpointsResponse)(nil), // 10: api_catalog.ListEndpointsResponse
	(*CreateServiceRequest)(nil),  // 11: api_catalog.CreateServiceRequest
	(*UpdateServiceRequest)(nil),  // 12: api_catalog.UpdateServiceRequest
	(*UpdateEndpointRequest)(nil), // 13: api_catalog.UpdateEndpointRequest
	(*DeleteServiceRequest)(nil),  // 14: api_catalog.DeleteServiceRequest
	(*DeleteServiceResponse)(nil), // 15: api_catalog.DeleteServiceResponse
	(*RescanAllRequest)(nil),      // 16: api_catalog.RescanAllRequest
	(*RescanServiceRequest)(nil),  // 17: api_catalog.RescanServiceRequest
	(*RescanReport)(nil),          // 18: api_catalog.RescanReport
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_api_catalog_proto_depIdxs = []int32{
	0,  // 0: api_catalog.Service.protocols:type_name -> api_catalog.Protocol
	1,  // 1: api_catalog.Service.source:type_name -> api_catalog.Source
	2,  // 2: api_catalog.Service.status:type_name -> api_catalog.Status
	19, // 3: api_catalog.Service.last_scanned_at:type_name -> google.protobuf.Timestamp
	19, // 4: api_catalog.Service.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: api_catalog.Service.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: api_catalog.Service.auth_policy:type_name -> api_catalog.AuthPolicy
	0,  // 7: api_catalog.Endpoint.protocol:type_name -> api_catalog.Protocol
	3,  // 8: api_catalog.Endpoint.auth_policy:type_name -> api_catalog.AuthPolicy
	4,  // 9: api_catalog.ListServicesResponse.items:type_name -> api_catalog.Service
	0,  // 10: api_catalog.ListEndpointsRequest.protocol:type_name -> api_catalog.Protocol
	5,  // 11: api_catalog.ListEndpointsResponse.items:type_name -> api_catalog.Endpoint
	0,  // 12: api_catalog.CreateServiceRequest.protocols:type_name -> api_catalog.Protocol
	3,  // 13: api_catalog.CreateServiceRequest.auth_policy:type_name -> api_catalog.AuthPolicy
	2,  // 14: api_catalog.UpdateServiceRequest.status:type_name -> api_catalog.Status
	3,  // 15: api_catalog.UpdateServiceRequest.auth_policy:type_name -> api_catalog.AuthPolicy
	3,  // 16: api_catalog.UpdateEndpointRequest.auth_policy:type_name -> api_catalog.AuthPolicy
	19, // 17: api_catalog.RescanReport.finished_at:type_name -> google.protobuf.Timestamp
	6,  // 18: api_catalog.ApiCatalog.ListServices:input_type -> api_catalog.ListServicesRequest
	8,  // 19: api_catalog.ApiCatalog.GetService:input_type -> api_catalog.GetServiceRequest
	9,  // 20: api_catalog.ApiCatalog.ListEndpoints:input_type -> api_catalog.ListEndpointsRequest
	11, // 21: api_catalog.ApiCatalog.CreateService:input_type -> api_catalog.CreateServiceRequest
	12, // 22: api_catalog.ApiCatalog.UpdateService:input_type -> api_catalog.UpdateServiceRequest
	14, // 23: api_catalog.ApiCatalog.DeleteService:input_type -> api_catalog.DeleteServiceRequest
	13, // 24: api_catalog.ApiCatalog.UpdateEndpoint:input_type -> api_catalog.UpdateEndpointRequest
	16, // 25: api_catalog.ApiCatalog.RescanAll:input_type -> api_catalog.RescanAllRequest
	17, // 26: api_catalog.ApiCatalog.RescanService:input_type -> api_catalog.RescanServiceRequest
	7,  // 27: api_catalog.ApiCatalog.ListServices:output_type -> api_catalog.ListServicesResponse
	4,  // 28: api_catalog.ApiCatalog.GetService:output_type -> api_catalog.Service
	10, // 29: api_catalog.ApiCatalog.ListEndpoints:output_type -> api_catalog.ListEndpointsResponse
	4,  // 30: api_catalog.ApiCatalog.CreateService:output_type -> api_catalog.Service
	4,  // 31: api_catalog.ApiCatalog.UpdateService:output_type -> api_catalog.Service
	15, // 32: api_catalog.ApiCatalog.DeleteService:output_type -> api_catalog.DeleteServiceResponse
	5,  // 33: api_catalog.ApiCatalog.UpdateEndpoint:output_type -> api_catalog.Endpoint
	18, // 34: api_catalog.ApiCatalog.RescanAll:output_type -> api_catalog.RescanReport
	18, // 35: api_catalog.ApiCatalog.RescanService:output_type -> api_catalog.RescanReport
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_catalog_proto_init() }
func file_api_catalog_proto_init() {
	if File_api_catalog_proto != nil {
		return
	}
	file_api_catalog_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_catalog_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_catalog_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_catalog_proto_rawDesc), len(file_api_catalog_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_catalog_proto_goTypes,
		DependencyIndexes: file_api_catalog_proto_depIdxs,
		EnumInfos:         file_api_catalog_proto_enumTypes,
		MessageInfos:      file_api_catalog_proto_msgTypes,
	}.Build()
	File_api_catalog_proto = out.File
	file_api_catalog_proto_goTypes = nil
	file_api_catalog_proto_depIdxs = nil
}
