version: '3.8'

services:
  model-builder:
    build:
      context: .
      dockerfile: ./model-optimizer/Dockerfile
    volumes:
      # Monte le répertoire local pour que les modèles ONNX y soient écrits
      - ./triton-model-repo:/output
    # Exécute les deux scripts l'un après l'autre. Le conteneur s'arrêtera après.
    command: /bin/bash -c "python export_embedding_to_onnx.py && python export_reranker_to_onnx.py"
  vllm-server:
    image: vllm/vllm-openai:latest
    command: >
      --model Qwen/Qwen3-14B-AWQ
      --quantization awq
      --trust-remote-code
      --max-model-len 4096
      --gpu-memory-utilization 0.75
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # count: all
              capabilities: [gpu]
    volumes:
      - /mnt/data/docker/images/huggingface_cache:/root/.cache/huggingface
    networks:
      - services-net

  triton-server:
    image: nvcr.io/nvidia/tritonserver:24.01-py3 # Utilisez une image récente
    command: tritonserver --model-repository=/models --log-verbose=1
    ports:
      - "8001:8001" # Port gRPC de Triton
      - "8002:8002" # Port de métriques
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              # count: all
              capabilities: [gpu]
    volumes:
      - ./triton-model-repo:/models
    networks:
      - services-net

  # --- Services Applicatifs (Clients) ---

  llm-service:
    build:
      context: .
      dockerfile: ./apps-microservices/llm-service/Dockerfile
    environment:
      - VLLM_API_URL=http://vllm-server:8000/v1/chat/completions
    depends_on:
      - vllm-server
    networks:
      - services-net

  embedding-model-service:
    build:
      context: .
      dockerfile: ./apps-microservices/embedding-model-service/Dockerfile
    # Le GPU n'est plus nécessaire ici, Triton s'en charge !
    environment:
      - TRITON_URL=triton-server:8001
    depends_on:
      - triton-server
    networks:
      - services-net

  reranking-model-service:
    build:
      context: .
      dockerfile: ./apps-microservices/reranking-model-service/Dockerfile
    # Le GPU n'est plus nécessaire ici
    environment:
      - TRITON_URL=triton-server:8001
    depends_on:
      - triton-server
    networks:
      - services-net

  database-recherche-service:
    build:
      context: .
      dockerfile: ./apps-microservices/database-recherche-service/Dockerfile
    env_file:
      - .env
    networks:
      - services-net

  api-model-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-model-service/Dockerfile
    ports:
      - "8599:8599"
    environment:
      - LLM_SERVICE_URL=llm-service:50051
      - EMBEDDING_SERVICE_URL=embedding-model-service:50052
      - RERANKING_SERVICE_URL=reranking-model-service:50053
      - DATABASE_SERVICE_URL=database-recherche-service:50054
    depends_on:
      - llm-service
      - embedding-model-service
      - reranking-model-service
      - database-recherche-service
    networks:
      - services-net

  api-ingestion-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-ingestion/Dockerfile
    container_name: api-ingestion-service
    restart: unless-stopped
    ports:
      - "8509:8509"
    env_file:
      - .env

  api-recherche-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-recherche/Dockerfile
    container_name: api-recherche-service
    restart: unless-stopped
    # TODO: à supprimer en PROD
    # volumes:
    #   - ./apps-microservices/api-recherche:/app:rw
    ports:
      - "8510:8510"
    environment:
      - LLM_SERVICE_URL=llm-service:50051
      - EMBEDDING_SERVICE_URL=embedding-model-service:50052
      - RERANKING_SERVICE_URL=reranking-model-service:50053
      - DATABASE_SERVICE_URL=database-recherche-service:50054
    depends_on:
      - llm-service
      - embedding-model-service
      - reranking-model-service
      - database-recherche-service
    env_file:
      - .env
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    networks:
      - services-net

  api-chat-llm-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-chat-llm/Dockerfile
    container_name: api-chat-llm-service
    restart: unless-stopped
    ports:
      - "8540:8540"
    environment:
      - LLM_SERVICE_URL=llm-service:50051
    depends_on:
      - llm-service
    env_file:
      - .env
    networks:
      - services-net


  api-classification-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-classification/Dockerfile
    container_name: api-classification-service
    restart: unless-stopped
    # TODO: à supprimer en PROD
    volumes:
      - ./apps-microservices/api-classification:/app:rw
    ports:
      - "8520:8520"
    env_file:
      - .env
  
  api-html-recherche-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-html-recherche/Dockerfile
    container_name: api-html-recherche-service
    restart: unless-stopped
    # TODO: à supprimer en PROD
    volumes:
      - ./apps-microservices/api-html-recherche:/app:rw
      - ./libs:/app/libs:rw
    ports:
      - "8550:8550"
    env_file:
      - .env

  api-gateway-service:
    build:
      context: .
      dockerfile: ./apps-microservices/api-gateway/Dockerfile
    container_name: api-gateway-service
    volumes:
      - ./apps-microservices/api-gateway:/app:rw
    restart: unless-stopped
    ports:
      - "8500:8500"
    env_file:
      - .env

  devis-processor-service:
    build:
      context: .
      dockerfile: ./apps-microservices/devis-processor-service/Dockerfile
    # container_name: devis-processor-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  echange-processor-service:
    build:
      context: .
      dockerfile: ./apps-microservices/echange-processor-service/Dockerfile
    # container_name: echange-processor-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  website-processor-service:
    build:
      context: .
      dockerfile: ./apps-microservices/website-processor-service/Dockerfile
    # container_name: website-processor-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  product-processor-service:
    build:
      context: .
      dockerfile: ./apps-microservices/product-processor-service/Dockerfile
    # container_name: product-processor-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  categories-processor-service:
    build:
      context: .
      dockerfile: ./apps-microservices/categories-processor-service/Dockerfile
    # container_name: categories-processor-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  fournisseurs-processor-service:
    build:
      context: .
      dockerfile: ./apps-microservices/fournisseurs-processor-service/Dockerfile
    # container_name: fournisseurs-processor-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  template-llm-service:
    build:
      context: .
      dockerfile: ./apps-microservices/template-llm-service/Dockerfile
    container_name: template-llm-service
    restart: unless-stopped
    volumes:
      - ./apps-microservices/template-llm-service/app:/app/template_llm_service:rw
    env_file:
      - .env
    
    # SOLUTION PRINCIPALE : Mémoire partagée pour NCCL
    shm_size: '16gb'  # Essentiel pour la communication inter-GPU
    
    # Variables d'environnement pour optimiser NCCL et multi-GPU
    environment:
      - NCCL_DEBUG=INFO           # Debug NCCL pour diagnostiquer les problèmes
      - NCCL_SHM_DISABLE=0        # Active la mémoire partagée NCCL
      - NCCL_P2P_DISABLE=0        # Active la communication P2P entre GPUs
      - NCCL_IB_DISABLE=1         # Désactive InfiniBand (pas nécessaire)
      - NCCL_SOCKET_IFNAME=eth0   # Interface réseau pour NCCL
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512  # Optimise l'allocateur CUDA
      - TORCH_NCCL_BLOCKING_WAIT=1  # Évite les timeouts NCCL
    
    # Configuration GPU optimisée
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Optimisations système pour les performances
    ulimits:
      memlock: -1      # Pas de limite sur la mémoire verrouillée
      stack: 67108864  # Stack plus grande pour les threads CUDA
              
  embedding-service:
    build:
      context: .
      dockerfile: ./apps-microservices/embedding-service/Dockerfile
    # container_name: embedding-service
    restart: unless-stopped
    environment:
      - LLM_SERVICE_URL=llm-service:50051
      - EMBEDDING_SERVICE_URL=embedding-model-service:50052
      - RERANKING_SERVICE_URL=reranking-model-service:50053
      - DATABASE_SERVICE_URL=database-recherche-service:50054
    depends_on:
      - embedding-model-service
    env_file:
      - .env
    volumes:
      - ./apps-microservices/embedding-service/app:/app/embedding_service:rw
    deploy:
      replicas: 4
      # resources:
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         #count: all
      #         device_ids: ['0']
      #         capabilities: [gpu]
    networks:
      - services-net

  di-database-qdrant-service:
    build:
      context: .
      dockerfile: ./apps-microservices/di-database-qdrant-service/Dockerfile
    # container_name: di-database-qdrant-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 12

  echange-database-qdrant-service:
    build:
      context: .
      dockerfile: ./apps-microservices/echange-database-qdrant-service/Dockerfile
    # container_name: echange-database-qdrant-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  website-database-qdrant-service:
    build:
      context: .
      dockerfile: ./apps-microservices/website-database-qdrant-service/Dockerfile
    # container_name: website-database-qdrant-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4
  
  product-database-qdrant-service:
    build:
      context: .
      dockerfile: ./apps-microservices/product-database-qdrant-service/Dockerfile
    # container_name: product-database-qdrant-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 20

  categories-database-qdrant-service:
    build:
      context: .
      dockerfile: ./apps-microservices/categories-database-qdrant-service/Dockerfile
    # container_name: categories-database-qdrant-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  fournisseurs-database-qdrant-service:
    build:
      context: .
      dockerfile: ./apps-microservices/fournisseurs-database-qdrant-service/Dockerfile
    # container_name: fournisseurs-database-qdrant-service
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 4

  webhook-service:
    build:
      context: .
      dockerfile: ./apps-microservices/webhook-service/Dockerfile
    container_name: webhook-service
    restart: unless-stopped
    env_file:
      - .env
  api-rest-milvus-service:
      build:
        context: .
        dockerfile: ./apps-microservices/api-rest-milvus/Dockerfile
      container_name: api-rest-milvus
      restart: unless-stopped
      ports:
        - "8515:8515"
      env_file:
        - .env

  api-check-doublon-produit:
    build:
      context: .
      dockerfile: ./apps-microservices/api-check-doublon-produit/Dockerfile
    container_name: api-check-doublon-produit
    restart: unless-stopped
    ports:
      - "8516:8516"
    env_file:
      - .env

  optimize-service:
    build:
      context: .
      dockerfile: ./apps-microservices/optimize-service/Dockerfile
    container_name: optimize-service
    restart: unless-stopped
    # TODO: à supprimer en PROD
    volumes:
      - ./apps-microservices/optimize-service:/app:rw
    ports:
      - "8563:8563"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              # count: all
              capabilities: [gpu]
networks:
  services-net:
    driver: bridge
    