global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-ingestion-service'
    static_configs:
      - targets: ['api-ingestion-service:8509']

  - job_name: 'website-processor-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - tasks.website-processor-service # The service name defined in docker-compose
      type: 'A'
      port: 8530