global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-ingestion-service'
    static_configs:
      - targets: ['api-ingestion-service:8509']

  - job_name: 'website-processor-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - website-processor-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'website-database-qdrant-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - website-database-qdrant-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'embedding-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - embedding-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'embedding-model-service'
    dns_sd_configs:
    - names:
      - embedding-model-service
      type: 'A'
      port: 8530

  - job_name: 'reranking-model-service'
    dns_sd_configs:
    - names:
      - reranking-model-service
      type: 'A'
      port: 8530

  - job_name: 'template-llm-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - template-llm-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'devis-processor-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - devis-processor-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'di-database-qdrant-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - di-database-qdrant-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'echange-processor-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - echange-processor-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'echange-database-qdrant-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - echange-database-qdrant-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'product-processor-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - product-processor-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'product-database-qdrant-service'
    # This uses Docker's internal DNS to find all running container instances (replicas) of this service
    dns_sd_configs:
    - names:
      - product-database-qdrant-service # The service name defined in docker-compose
      type: 'A'
      port: 8530

  - job_name: 'api-classification-service'
    dns_sd_configs:
    - names:
      - api-classification-service # The service name from docker-compose
      type: 'A'
      port: 8577 # The internal port of the service

  - job_name: 'optimize-service'
    static_configs:
      - targets: ['optimize-service:8563'] # The service name and port from docker-compose

  - job_name: 'document-database-qdrant-service'
    dns_sd_configs:
    - names:
      - document-database-qdrant-service
      type: 'A'
      port: 8530

  - job_name: 'database-recherche-service'
    static_configs:
      - targets: ['database-recherche-service:8530']

  - job_name: 'ressource-vm'
    scrape_interval: 5s
    static_configs:
      - targets:
         - node_exporter:9100

  - job_name: 'milvus-querynodes'
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets: ['10.0.1.197:9091']
    # Optionnel mais utile pour Grafana : ajouter un label explicite
    # relabel_configs:
    #   - target_label: instance
    #     replacement: 'querynode-cluster'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'querynode-cluster'

 
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      #- targets: ['cadvisor:8080']
       - targets:
          - cadvisor_exporter_vm_gpu:8080
          # - cadvisor:8080
