-- Seed généré depuis graph-rag-normalize-unite-service (origine='seed').
-- Régénérer via: python -m scripts.seed_referentiel_unite

-- unite_definition_ia
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('unité = count = unite = Nb = nb', 0, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('pieds = foot = pied', 1, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('decibel = [sound] = dB = dBA', 2, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('cheval = 735.49875 * watt = ch', 3, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('chevaux = count', 4, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('segments = count = segment', 5, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('mètres = meter', 6, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('Litres = liter', 7, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('Volts = volt', 8, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('sélections = count = selections = selection = sélection', 9, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('galettes = count = galette = Galettes = Galette', 10, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('tasses_par_jour = count', 11, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('Watts = watt', 12, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('unités = count', 13, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('billets = count = billet', 14, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('pièces = count = pièce', 15, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('personnes = count = personne', 16, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('degré = degree = degre = degrés = degres', 17, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('Tonnes = tonne', 18, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('démarrages = count = démarrage', 19, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('lignes = count = ligne', 20, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('tours_par_minute_fr = revolutions_per_minute', 21, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('pouces = 0.0254 * meter = pouce = inch_fr', 22, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('semelles_unit = count = semelles = semelle', 23, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('plots_unit = count = plots = plot', 24, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('bacs_unit = count = bacs = bac', 25, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('vehicules_unit = count = vehicules = vehicule', 26, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('recettes_par_programme = count', 27, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('coups_par_minute = count / minute', 28, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('coupes_par_minute = count / minute', 29, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('tonne = 1000 * kilogram = t', 30, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('mm = millimeter', 31, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('cm = centimeter', 32, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('m = meter', 33, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('kg = kilogram', 34, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('KW = 1000 * watt', 35, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('kw = 1000 * watt', 36, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('cheval_vapeur = 735.49875 * watt = cv', 37, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('CV = cheval_vapeur', 38, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('V = volt', 39, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('A = ampere', 40, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('sec = second', 41, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('ph = hertz', 42, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('tours_par_minute = revolutions_per_minute = rpm = tr/min = trs/min', 43, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('Pa = pascal', 44, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('kPa = 1000 * pascal', 45, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('L_par_min = liter / minute = l/min', 46, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('L_par_h = liter / hour = l/h', 47, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('m3_par_h = meter**3 / hour', 48, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('m3 = meter**3', 49, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('litres = liter', 50, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('L = liter', 51, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('N = newton', 52, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('kgf = 9.80665 * newton', 53, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('Nm = newton * meter', 54, 'seed');
INSERT INTO unite_definition_ia (definition_udfi, ordre_udfi, origine_udfi) VALUES ('kg_par_m2 = kilogram / meter ** 2 = kg/m² = kg/m2', 55, 'seed');

-- unite_dimension_ia
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('unité', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('unités', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('unite', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('unites', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('nb', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('chevaux', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('segments', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('segment', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('sélections', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('selections', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('sélection', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('selection', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('galettes', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('galette', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tasses/jour', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tasses_par_jour', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('billets', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('billet', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pièces', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pièce', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('personnes', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('personne', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('lignes', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ligne', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('db', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('dba', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('db(a)', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('decibel', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('g', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('t', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tonne', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tonnes', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mm', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cm', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('km', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pieds', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pied', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mètres', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pouces', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pouce', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/m³', 'density', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/m3', 'density', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('w', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('watts', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kw', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cv', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ch', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('hp', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('v', 'voltage', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('volts', 'voltage', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('a', 'current', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('rpm', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tr/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('trs/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tours/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('tour/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('démarrages/heure', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('hz', 'frequency', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('l', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('litres', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ml', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m3', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m**3', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('°c', 'temperature', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('c', 'temperature', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('k', 'temperature', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('bar', 'pressure', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pa', 'pressure', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kpa', 'pressure', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('psi', 'pressure', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('s', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('sec', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('min', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('h', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('l/min', 'volume / time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('l/h', 'volume / time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m3/h', 'volume / time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m³/h', 'volume / time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('débit', 'volume / time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('g/min', 'mass_flow', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/min', 'mass_flow', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/h', 'mass_flow', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pièces/seconde', 'count_rate', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pieces/seconde', 'count_rate', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('billets/seconde', 'count_rate', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('n', 'force', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kn', 'force', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kgf', 'force', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('force', 'force', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('poussée', 'force', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('traction', 'force', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('nm', 'torque', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('couple', 'torque', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/m2', 'area_density', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/m²', 'area_density', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('volume', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cuve', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('contenance', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mémoire', 'information', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('stockage', 'information', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('énergie', 'energy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kwh', 'energy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('wh', 'energy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kwh/24h', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('consommation', 'energy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('surface', 'area', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('superficie', 'area', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('°', 'angle', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('deg', 'angle', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('degré', 'angle', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('degrés', 'angle', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('degre', 'angle', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('degres', 'angle', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('l/cycle', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('signal', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('signaux', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('plateaux', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('plateau', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('lm', 'luminosity', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('lm/w', 'luminous_efficacy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ra', 'dimensionless', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('%', 'ratio', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('km/h', 'speed', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('semelles', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('semelle', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('plots', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('plot', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('bacs', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('bac', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('véhicule(s)', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('véhicules', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('véhicule', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('vehicule(s)', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('vehicules', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('vehicule', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('recettes/programmes', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('coups/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('coupes/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('μm', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('um', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('minutes', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kg/24h', 'mass_flow', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m²/h', 'surface_rate', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m2/h', 'surface_rate', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('w/m².k', 'thermal_transmittance', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('w/m2.k', 'thermal_transmittance', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m².k/w', 'thermal_resistance', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m2.k/w', 'thermal_resistance', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('t/min', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('heures', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('heure', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('t/h', 'mass_flow', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mohs', 'dimensionless', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('go', 'information', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mo', 'information', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ko', 'information', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('to', 'information', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('px', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pixel', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pixels', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kn/m²', 'pressure', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kn/m2', 'pressure', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m³', 'volume', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cd/m²', 'luminance', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cd/m2', 'luminance', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ah', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('a.h', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('amperes-heures', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ampere-heure', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ampères-heures', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('ampère-heure', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mah', 'electric_charge', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kilogrammes', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kilogramme', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('grammes', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('gramme', 'mass', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('millimètres', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('millimètre', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('centimètres', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('centimètre', 'length', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('décibels', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('décibel', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('decibels', 'sound_level', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m²', 'area', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('m2', 'area', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('niveau', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('niveaux', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cycles/jour', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cycles / jour', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kwh/kg', 'specific_energy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kwh / kg', 'specific_energy', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('kwc', 'power', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cycles', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cycle', 'count', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('mpa.s', 'viscosity', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('pa.s', 'viscosity', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('cycles par jour', '[frequency]', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('secondes', 'time', 'seed');
INSERT INTO unite_dimension_ia (unite_udi, dimension_udi, origine_udi) VALUES ('seconde', 'time', 'seed');

-- label_dimension_ia
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('charge au sol', 'area_density', 0, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('charge admissible au sol', 'area_density', 1, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('charge statique', 'area_density', 2, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('classe climatique', 'count', 3, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('régime', '[frequency]', 4, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('nombre', 'count', 5, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('quantité', 'count', 6, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('segment', 'count', 7, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('segments', 'count', 8, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('sélections', 'count', 9, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('selections', 'count', 10, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité volumique', 'volume', 11, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité volumétrique', 'volume', 12, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité de stockage (masse)', 'mass', 13, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité de stockage', 'count', 14, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité totale de stockage', 'count', 15, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité d''accueil', 'count', 16, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité de la vitrine', 'count', 17, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité de production', 'mass_flow', 18, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité de la batterie', 'electric_charge', 19, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('recycleur', 'count', 20, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('cassette de délestage', 'count', 21, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('bac de trop-plein', 'count', 22, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('passagers', 'count', 23, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('sonore', 'sound_level', 24, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('acoustique', 'sound_level', 25, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('bruit', 'sound_level', 26, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('decibel', 'sound_level', 27, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('poids', 'mass', 28, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('charge', 'mass', 29, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('capacité', 'mass', 30, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('hauteur', 'length', 31, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('largeur', 'length', 32, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('longueur', 'length', 33, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('profondeur', 'length', 34, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('diamètre', 'length', 35, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('dimension', 'length', 36, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('distance', 'length', 37, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('epaisseur', 'length', 38, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('vitesse de rotation', '[frequency]', 39, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('vitesse d''acceptation', 'count_rate', 40, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('vitesse de distribution', 'count_rate', 41, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('vitesse de nettoyage', 'surface_rate', 42, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('vitesse', 'speed', 43, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('puissance', 'power', 44, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('tension', 'voltage', 45, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('courant', 'current', 46, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('fusible', 'current', 47, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('branchement', 'voltage', 48, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('fréquence d''utilisation', '[frequency]', 49, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('fréquence', 'frequency', 50, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('tours/minute', '[frequency]', 51, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('volume', 'volume', 52, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('cuve', 'volume', 53, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('contenance', 'volume', 54, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('température', 'temperature', 55, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('pression', 'pressure', 56, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('temps', 'time', 57, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('duree', 'time', 58, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('delai', 'time', 59, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('mémoire', 'information', 60, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('stockage', 'information', 61, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('débit de vapeur', 'mass_flow', 62, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('consommation d''eau', 'volume', 63, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('consommation électrique', 'power', 64, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('autonomie de la batterie', 'time', 65, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('batterie', 'energy', 66, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('consommation', 'energy', 67, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('débit', 'volume / time', 68, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('force', 'force', 69, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('poussée', 'force', 70, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('traction', 'force', 71, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('couple', 'torque', 72, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('énergie', 'energy', 73, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('surface', 'area', 74, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('superficie', 'area', 75, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('angle', 'angle', 76, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('rotation', 'angle', 77, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('production horaire', 'volume / time', 78, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('déverrouillage', 'count', 79, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('lignes hydrauliques', 'count', 80, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('niveaux desservis', 'count', 81, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('cylindres', 'count', 82, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('plateaux', 'count', 83, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('configuration de la base', 'count', 84, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('catégorie cabine', 'count', 85, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('mémorisation de programmes', 'count', 86, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('cadence', '[frequency]', 87, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('coefficient de transmission thermique', 'thermal_transmittance', 88, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('résistance thermique', 'thermal_resistance', 89, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('résolution de l''écran', 'count', 90, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('luminosité de l''écran', 'luminance', 91, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('dureté', 'dimensionless', 92, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('mémoire vive', 'information', 93, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('ratio masse/volume', 'density', 94, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('ratio puissance/poids', 'power', 95, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('ratio de compression', 'pressure', 96, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('ratio de réduction', 'ratio', 97, 'seed');
INSERT INTO label_dimension_ia (label_ldi, dimension_ldi, priorite_ldi, origine_ldi) VALUES ('ratio', 'ratio', 98, 'seed');

-- dimension_canonique_ia
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('count', 'count', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('sound_level', 'decibel', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('mass', 'kilogram', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('length', 'meter', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('speed', 'meter / second', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('power', 'watt', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('voltage', 'volt', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('current', 'ampere', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('frequency', 'hertz', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('[frequency]', 'hertz', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('volume', 'liter', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('temperature', 'celsius', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('pressure', 'bar', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('time', 'second', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('information', 'gigabyte', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('volume / time', 'liter / minute', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('force', 'newton', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('torque', 'newton * meter', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('energy', 'joule', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('area', 'meter ** 2', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('area_density', 'kilogram / meter ** 2', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('density', 'kilogram / meter ** 3', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('angle', 'degree', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('mass_flow', 'gram / minute', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('count_rate', 'count / second', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('luminosity', 'lumen', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('luminous_efficacy', 'lumen / watt', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('ratio', 'count', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('dimensionless', 'count', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('thermal_transmittance', 'watt / meter ** 2 / kelvin', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('thermal_resistance', 'meter ** 2 * kelvin / watt', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('surface_rate', 'meter ** 2 / hour', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('luminance', 'candela / meter ** 2', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('electric_charge', 'ampere_hour', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('specific_energy', 'joule / kilogram', 'seed');
INSERT INTO dimension_canonique_ia (dimension_dci, unite_canonique_dci, origine_dci) VALUES ('viscosity', 'pascal * second', 'seed');

-- unite_preprocessing_ia
INSERT INTO unite_preprocessing_ia (type_upi, phase_upi, pattern_upi, remplacement_upi, ordre_upi, origine_upi) VALUES ('nfkc', 'pre_snapshot', NULL, '', 0, 'seed');
INSERT INTO unite_preprocessing_ia (type_upi, phase_upi, pattern_upi, remplacement_upi, ordre_upi, origine_upi) VALUES ('regex_sub', 'pre_snapshot', '\\s*\\([^)]*\\)\\s*$', '', 1, 'seed');
INSERT INTO unite_preprocessing_ia (type_upi, phase_upi, pattern_upi, remplacement_upi, ordre_upi, origine_upi) VALUES ('str_replace', 'pre_snapshot', '·', '.', 2, 'seed');
INSERT INTO unite_preprocessing_ia (type_upi, phase_upi, pattern_upi, remplacement_upi, ordre_upi, origine_upi) VALUES ('str_replace', 'post_snapshot', '³', '3', 3, 'seed');
INSERT INTO unite_preprocessing_ia (type_upi, phase_upi, pattern_upi, remplacement_upi, ordre_upi, origine_upi) VALUES ('str_replace', 'post_snapshot', '²', '2', 4, 'seed');

-- unite_reecriture_ia
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('db(a)', 'rewrite', 'dBA', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('tr/min', 'rewrite', 'rpm', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('trs/min', 'rewrite', 'rpm', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('m3/h', 'rewrite', 'm**3 / hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('m2', 'rewrite', 'm**2', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('m3', 'rewrite', 'm**3', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kg/m2', 'rewrite', 'kilogram / meter ** 2', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kg/m3', 'rewrite', 'kilogram / meter ** 3', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('g/min', 'rewrite', 'gram / minute', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pièces/seconde', 'rewrite', 'count / second', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pieces/seconde', 'rewrite', 'count / second', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('billets/seconde', 'rewrite', 'count / second', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('tasses/jour', 'rewrite', 'count', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('watts', 'rewrite', 'watt', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kwh/24h', 'rewrite', 'kilowatt_hour / day', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('l/cycle', 'rewrite', 'liter', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('tonnes', 'rewrite', 'tonne', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pieds', 'rewrite', 'pieds', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pied', 'rewrite', 'pieds', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('démarrages/heure', 'rewrite', '1 / hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('tours/min', 'rewrite', 'rpm', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('tour/min', 'rewrite', 'rpm', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('lignes', 'rewrite', 'count', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ligne', 'rewrite', 'count', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pouces', 'rewrite', 'inch', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pouce', 'rewrite', 'inch', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('km/h', 'rewrite', 'kilometer / hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('lm/w', 'rewrite', 'lumen / watt', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('%', 'bypass', 'count', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ra', 'bypass', 'count', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('minutes', 'rewrite', 'minute', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('μm', 'rewrite', 'micrometer', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kg/24h', 'rewrite', 'kilogram / day', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('m2/h', 'rewrite', 'meter ** 2 / hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('w/m2.k', 'rewrite', 'watt / (meter ** 2 * kelvin)', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('m2.k/w', 'rewrite', 'meter ** 2 * kelvin / watt', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('coups/min', 'rewrite', '1 / minute', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('coupes/min', 'rewrite', '1 / minute', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('heures', 'rewrite', 'hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('heure', 'rewrite', 'hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('go', 'rewrite', 'gigabyte', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('mo', 'rewrite', 'megabyte', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ko', 'rewrite', 'kilobyte', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('to', 'rewrite', 'terabyte', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('mohs', 'bypass', 'count', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kn/m2', 'rewrite', 'kilonewton / meter ** 2', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('cd/m2', 'rewrite', 'candela / meter ** 2', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ah', 'rewrite', 'ampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('a.h', 'rewrite', 'ampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('amperes-heures', 'rewrite', 'ampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ampere-heure', 'rewrite', 'ampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ampères-heures', 'rewrite', 'ampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('ampère-heure', 'rewrite', 'ampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('mah', 'rewrite', 'milliampere_hour', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kilogrammes', 'rewrite', 'kilogram', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kilogramme', 'rewrite', 'kilogram', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('grammes', 'rewrite', 'gram', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('gramme', 'rewrite', 'gram', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('millimètres', 'rewrite', 'millimeter', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('millimètre', 'rewrite', 'millimeter', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('centimètres', 'rewrite', 'centimeter', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('centimètre', 'rewrite', 'centimeter', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('décibels', 'rewrite', 'decibel', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('décibel', 'rewrite', 'decibel', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('decibels', 'rewrite', 'decibel', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('decibel', 'rewrite', 'decibel', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('cycles/jour', 'rewrite', '1 / day', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('cycles / jour', 'rewrite', '1 / day', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kwh/kg', 'rewrite', 'kilowatt_hour / kilogram', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kwh / kg', 'rewrite', 'kilowatt_hour / kilogram', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('kwc', 'rewrite', 'kilowatt', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('mpa.s', 'rewrite', 'millipascal * second', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('pa.s', 'rewrite', 'pascal * second', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('cycles par jour', 'rewrite', '1 / day', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('secondes', 'rewrite', 'second', 'seed');
INSERT INTO unite_reecriture_ia (unite_source_uri, kind_uri, value_uri, origine_uri) VALUES ('seconde', 'rewrite', 'second', 'seed');
