// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api_catalog.proto

package api_catalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiCatalog_ListServices_FullMethodName  = "/api_catalog.ApiCatalog/ListServices"
	ApiCatalog_GetService_FullMethodName    = "/api_catalog.ApiCatalog/GetService"
	ApiCatalog_ListEndpoints_FullMethodName = "/api_catalog.ApiCatalog/ListEndpoints"
	ApiCatalog_CreateService_FullMethodName = "/api_catalog.ApiCatalog/CreateService"
	ApiCatalog_UpdateService_FullMethodName = "/api_catalog.ApiCatalog/UpdateService"
	ApiCatalog_DeleteService_FullMethodName = "/api_catalog.ApiCatalog/DeleteService"
	ApiCatalog_RescanAll_FullMethodName     = "/api_catalog.ApiCatalog/RescanAll"
	ApiCatalog_RescanService_FullMethodName = "/api_catalog.ApiCatalog/RescanService"
)

// ApiCatalogClient is the client API for ApiCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiCatalogClient interface {
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error)
	ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error)
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Service, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Service, error)
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error)
	RescanAll(ctx context.Context, in *RescanAllRequest, opts ...grpc.CallOption) (*RescanReport, error)
	RescanService(ctx context.Context, in *RescanServiceRequest, opts ...grpc.CallOption) (*RescanReport, error)
}

type apiCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewApiCatalogClient(cc grpc.ClientConnInterface) ApiCatalogClient {
	return &apiCatalogClient{cc}
}

func (c *apiCatalogClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ApiCatalog_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, ApiCatalog_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEndpointsResponse)
	err := c.cc.Invoke(ctx, ApiCatalog_ListEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, ApiCatalog_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, ApiCatalog_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceResponse)
	err := c.cc.Invoke(ctx, ApiCatalog_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) RescanAll(ctx context.Context, in *RescanAllRequest, opts ...grpc.CallOption) (*RescanReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescanReport)
	err := c.cc.Invoke(ctx, ApiCatalog_RescanAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiCatalogClient) RescanService(ctx context.Context, in *RescanServiceRequest, opts ...grpc.CallOption) (*RescanReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescanReport)
	err := c.cc.Invoke(ctx, ApiCatalog_RescanService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiCatalogServer is the server API for ApiCatalog service.
// All implementations must embed UnimplementedApiCatalogServer
// for forward compatibility.
type ApiCatalogServer interface {
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	GetService(context.Context, *GetServiceRequest) (*Service, error)
	ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error)
	CreateService(context.Context, *CreateServiceRequest) (*Service, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*Service, error)
	DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error)
	RescanAll(context.Context, *RescanAllRequest) (*RescanReport, error)
	RescanService(context.Context, *RescanServiceRequest) (*RescanReport, error)
	mustEmbedUnimplementedApiCatalogServer()
}

// UnimplementedApiCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiCatalogServer struct{}

func (UnimplementedApiCatalogServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedApiCatalogServer) GetService(context.Context, *GetServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedApiCatalogServer) ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (UnimplementedApiCatalogServer) CreateService(context.Context, *CreateServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedApiCatalogServer) UpdateService(context.Context, *UpdateServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedApiCatalogServer) DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedApiCatalogServer) RescanAll(context.Context, *RescanAllRequest) (*RescanReport, error) {
	return nil, status.Error(codes.Unimplemented, "method RescanAll not implemented")
}
func (UnimplementedApiCatalogServer) RescanService(context.Context, *RescanServiceRequest) (*RescanReport, error) {
	return nil, status.Error(codes.Unimplemented, "method RescanService not implemented")
}
func (UnimplementedApiCatalogServer) mustEmbedUnimplementedApiCatalogServer() {}
func (UnimplementedApiCatalogServer) testEmbeddedByValue()                    {}

// UnsafeApiCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiCatalogServer will
// result in compilation errors.
type UnsafeApiCatalogServer interface {
	mustEmbedUnimplementedApiCatalogServer()
}

func RegisterApiCatalogServer(s grpc.ServiceRegistrar, srv ApiCatalogServer) {
	// If the following call panics, it indicates UnimplementedApiCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiCatalog_ServiceDesc, srv)
}

func _ApiCatalog_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_ListEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).ListEndpoints(ctx, req.(*ListEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_RescanAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescanAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).RescanAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_RescanAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).RescanAll(ctx, req.(*RescanAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiCatalog_RescanService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescanServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiCatalogServer).RescanService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiCatalog_RescanService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiCatalogServer).RescanService(ctx, req.(*RescanServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiCatalog_ServiceDesc is the grpc.ServiceDesc for ApiCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_catalog.ApiCatalog",
	HandlerType: (*ApiCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _ApiCatalog_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ApiCatalog_GetService_Handler,
		},
		{
			MethodName: "ListEndpoints",
			Handler:    _ApiCatalog_ListEndpoints_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _ApiCatalog_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _ApiCatalog_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ApiCatalog_DeleteService_Handler,
		},
		{
			MethodName: "RescanAll",
			Handler:    _ApiCatalog_RescanAll_Handler,
		},
		{
			MethodName: "RescanService",
			Handler:    _ApiCatalog_RescanService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_catalog.proto",
}
