"""
Milvus connection utility and collection duplication logic.

Uses:
  - copy.deepcopy() to clone the source schema fields (preserves all params)
  - Milvus 2.6 built-in Function(BM25) for auto-generating sparse_embedding
  - query_iterator for streaming 1M+ rows in batches
"""

import os
import copy
import json
import logging
import time
from typing import Optional, List

from pymilvus import (
    connections,
    Collection,
    CollectionSchema,
    FieldSchema,
    DataType,
    Function,
    FunctionType,
    utility,
)

logging.basicConfig(level=logging.INFO, force=True)
logger = logging.getLogger(__name__)

# ── Milvus Connection Config ─────────────────────────────────────────────────
MILVUS_HOST = os.getenv("ZILLIZ_URI", "localhost")
MILVUS_TOKEN = os.getenv("ZILLIZ_TOKEN", "localhost")
MILVUS_PORT = os.getenv("ZILLIZ_PORT", "19530")
MILVUS_USER = os.getenv("ZILLIZ_USER", "")
MILVUS_PASSWORD = os.getenv("ZILLIZ_PASSWORD", "")

# ── Error Log Directory (bind-mounted volume) ────────────────────────────────
ERROR_LOG_DIR = os.getenv("ERROR_LOG_DIR", "/app/error_logs")


def connect_milvus():
    """Establish connection to Milvus using environment variables."""
    alias = "default"
    try:
        if not connections.has_connection(alias):
            logger.info(f"Connecting to Milvus at {MILVUS_HOST}:{MILVUS_PORT}")

            connections.connect(
                alias,
                host=MILVUS_HOST,
                port=MILVUS_PORT,
                user=MILVUS_USER,
                password=MILVUS_PASSWORD,
                # uri=MILVUS_HOST,
                # token=MILVUS_TOKEN if MILVUS_TOKEN else None,
            )
            logger.info("✅  Connected to Milvus")
    except Exception as e:
        logger.error(f"❌  Failed to connect to Milvus: {e}")
        raise


def build_target_schema(
    source: Collection,
    text_field: str = "text",
    analyzer_language: str = "english",
) -> CollectionSchema:
    """
    Clone the source schema and add a SPARSE_FLOAT_VECTOR field + BM25 Function.

    Uses copy.deepcopy() to preserve ALL field params (dim, max_length,
    element_type, max_capacity, etc.) without manual reconstruction.
    """
    new_fields = []
    text_field_found = False

    for field in source.schema.fields:
        cloned = copy.deepcopy(field)

        # Enable analyzer and match on the text field for BM25
        if cloned.name == text_field:
            text_field_found = True
            # We need to recreate this field with enable_analyzer and enable_match
            kwargs = dict(
                name=cloned.name,
                dtype=cloned.dtype,
                description=cloned.description,
                is_primary=cloned.is_primary,
                max_length=cloned.params.get("max_length", 65535),
                enable_analyzer=True,
                enable_match=True,
                analyzer_params={"type": analyzer_language},
            )
            cloned = FieldSchema(**kwargs)

        new_fields.append(cloned)

    if not text_field_found:
        raise ValueError(
            f"Text field '{text_field}' not found in source collection "
            f"'{source.name}'. Available fields: "
            f"{[f.name for f in source.schema.fields]}"
        )

    # Add the sparse_embedding output field
    new_fields.append(
        FieldSchema(
            name="sparse_embedding",
            dtype=DataType.SPARSE_FLOAT_VECTOR,
            description="Sparse vector auto-generated by Milvus BM25 Function",
        )
    )

    schema = CollectionSchema(
        fields=new_fields,
        description=f"Copy of '{source.name}' with sparse_embedding (BM25)",
        auto_id=source.schema.auto_id,
        enable_dynamic_field=True,
    )

    # Add the BM25 function linking text_field -> sparse_embedding
    bm25_function = Function(
        name="text_bm25_emb",
        input_field_names=[text_field],
        output_field_names=["sparse_embedding"],
        function_type=FunctionType.BM25,
    )
    schema.add_function(bm25_function)

    return schema


def copy_indexes(source: Collection, target: Collection):
    """Recreate all indexes from source on target, then add sparse index."""
    for idx in source.indexes:
        field_name = idx.field_name
        index_params = idx.params
        try:
            target.create_index(field_name=field_name, index_params=index_params)
            logger.info(f"   ↳ Index on '{field_name}' recreated")
        except Exception as e:
            logger.warning(f"   ⚠️  Could not recreate index on '{field_name}': {e}")

    # Create SPARSE_INVERTED_INDEX for the new sparse field
    target.create_index(
        field_name="sparse_embedding",
        index_params={
            "index_type": "SPARSE_INVERTED_INDEX",
            "metric_type": "BM25",
            "params": {"drop_ratio_build": 0.2},
        },
    )
    logger.info("   ↳ SPARSE_INVERTED_INDEX created on 'sparse_embedding'")


def _write_error_line(error_file_path: str, pk_value, row: dict, error: str):
    """Append one failed-row JSON line to the error log file."""
    # Convert any non-serializable values to strings
    safe_row = {}
    for k, v in row.items():
        try:
            json.dumps(v)
            safe_row[k] = v
        except (TypeError, ValueError):
            safe_row[k] = repr(v)

    line = json.dumps(
        {"pk": str(pk_value), "row": safe_row, "error": error},
        ensure_ascii=False,
    )
    with open(error_file_path, "a", encoding="utf-8") as f:
        f.write(line + "\n")


def duplicate_collection(
    source_name: str,
    target_name: str,
    text_field: str = "text",
    batch_size: int = 500,
    analyzer_language: str = "english",
    limit: Optional[int] = None,
    job_id: Optional[str] = None,
    job_state: Optional[dict] = None,
):
    """
    Duplicate a Milvus collection with all data, adding a sparse_embedding field.

    The BM25 Function in Milvus 2.6 auto-generates sparse vectors from the
    text field on insert — no Python-side BM25 computation needed.

    Args:
        source_name: Name of the source collection
        target_name: Name of the target collection to create
        text_field: VARCHAR field name used for BM25 generation
        batch_size: Number of records per insert batch
        analyzer_language: Language for the BM25 text analyzer
        limit: Optional max number of rows to migrate (for testing)
        job_id: Unique job ID used to name the error log file
        job_state: Mutable dict to track progress (updated in-place)
    """
    start_time = time.time()

    # ── Prepare error log file ──
    error_file_name = (
        f"errors_{job_id}.txt" if job_id else f"errors_{int(time.time())}.txt"
    )
    error_file_path = os.path.join(ERROR_LOG_DIR, error_file_name)
    os.makedirs(ERROR_LOG_DIR, exist_ok=True)
    total_skipped = 0

    # ── 1. Load source collection ──
    source = Collection(source_name)
    source.load()
    total_entities = source.num_entities
    logger.info(f"📦  Source: '{source_name}' ({total_entities} entities)")

    if job_state is not None:
        job_state["total_source_entities"] = total_entities

    # ── 2. Build new schema with sparse_embedding + BM25 Function ──
    schema = build_target_schema(source, text_field, analyzer_language)
    logger.info(f"📋  Schema built with {len(schema.fields)} fields + BM25 Function")

    # ── 3. Create target collection (drop if exists) ──
    if utility.has_collection(target_name):
        logger.warning(f"⚠️  '{target_name}' already exists – dropping it first.")
        utility.drop_collection(target_name)

    target = Collection(name=target_name, schema=schema)
    logger.info(f"✅  Created collection '{target_name}'")

    # ── 4. Recreate indexes ──
    copy_indexes(source, target)

    # ── 5. Migrate data using query_iterator ──
    # Only copy fields that are explicitly in the source schema
    # (exclude 'sparse_embedding' which Milvus BM25 Function fills automatically)
    schema_field_types = {f.name: f.dtype for f in source.schema.fields}
    # Build the set of fields the TARGET collection expects as input data:
    #   - all target schema fields MINUS auto-generated ones (sparse_embedding from BM25)
    target_auto_generated = set()
    for func in schema.functions:
        for out_name in func.output_field_names:
            target_auto_generated.add(out_name)
    # Also exclude PK field when auto_id=True (Milvus generates it)
    if schema.auto_id:
        pk_name = next((f.name for f in schema.fields if f.is_primary), None)
        if pk_name:
            target_auto_generated.add(pk_name)
    target_input_field_names = [
        f.name for f in schema.fields if f.name not in target_auto_generated
    ]
    # For querying the source, exclude fields that don't exist there
    source_field_set = {f.name for f in source.schema.fields}
    field_names = [fn for fn in target_input_field_names if fn in source_field_set]
    total_inserted = 0
    effective_total = limit if limit else total_entities

    # Find the primary key field name
    pk_field = next((f.name for f in source.schema.fields if f.is_primary), None)

    if limit:
        logger.info(
            f"⚠️  Limit set: migrating at most {limit} rows (out of {total_entities})"
        )

    logger.info(f"📋  Fields to copy: {field_names}")
    logger.info(
        f"📋  Field types: { {n: str(t) for n, t in schema_field_types.items()} }"
    )
    logger.info(
        f"📋  Auto-generated fields (excluded from insert): {target_auto_generated}"
    )

    iterator = source.query_iterator(
        expr="",
        output_fields=field_names,
        batch_size=batch_size,
    )

    while True:
        batch = iterator.next()
        if not batch:
            break

        # Trim batch if limit would be exceeded
        if limit and total_inserted + len(batch) > limit:
            batch = batch[: limit - total_inserted]

        # Log first row of first batch for debugging
        if total_inserted == 0 and batch:
            sample = {k: type(v).__name__ for k, v in batch[0].items()}
            logger.info(f"🔍  Sample row keys ({len(sample)}): {sample}")
            logger.info(
                f"📋  Target expects {len(target_input_field_names)} fields: {target_input_field_names}"
            )

        # Sanitize each row:
        #  - only keep fields in field_names (strict filter)
        #  - convert list/dict values to JSON for VARCHAR fields
        clean_batch = []
        for row in batch:
            clean_row = {}
            for field in field_names:
                val = row.get(field)
                if schema_field_types.get(field) == DataType.VARCHAR and isinstance(
                    val, (list, dict)
                ):
                    clean_row[field] = json.dumps(val, ensure_ascii=False)
                else:
                    clean_row[field] = val
            clean_batch.append(clean_row)

        # Build column-based data from clean rows.
        # Using column format (list of lists) prevents pymilvus from adding
        # an implicit $meta column that causes "more fieldData" errors.
        col_data = []
        for field in field_names:
            col_data.append([row[field] for row in clean_batch])

        if total_inserted == 0:
            logger.info(
                f"📋  Inserting {len(field_names)} columns × {len(clean_batch)} rows. "
                f"Columns: {field_names}"
            )

        # Insert batch — if it fails, fall back to row-by-row to identify bad rows
        try:
            target.insert(col_data)
            total_inserted += len(clean_batch)
        except Exception as batch_err:
            logger.warning(
                f"⚠️  Batch insert failed ({len(clean_batch)} rows): {batch_err}. "
                f"Falling back to row-by-row insert…"
            )
            for i, row in enumerate(clean_batch):
                try:
                    single_col = [[row[field]] for field in field_names]
                    target.insert(single_col)
                    total_inserted += 1
                except Exception as row_err:
                    pk_value = row.get(pk_field, "unknown") if pk_field else "unknown"
                    total_skipped += 1
                    logger.error(f"❌  Skipped row #{i} (pk={pk_value}): {row_err}")
                    # Log the problematic row's field values for debugging
                    for field_name, field_val in row.items():
                        logger.error(
                            f"      {field_name}: type={type(field_val).__name__}, "
                            f"value={repr(field_val)[:200]}"
                        )
                    # Write to error file
                    _write_error_line(error_file_path, pk_value, row, str(row_err))

        if job_state is not None:
            job_state["records_copied"] = total_inserted

        logger.info(f"   ↳ Copied {total_inserted}/{effective_total} records…")

        # Stop early if limit is reached
        if limit and total_inserted >= limit:
            logger.info(f"🛑  Limit of {limit} rows reached – stopping migration.")
            break

    iterator.close()

    # ── 6. Flush and load the target collection ──
    target.flush()
    target.load()

    elapsed = time.time() - start_time
    logger.info(
        f"\n🎉  Done!  Collection '{target_name}' is ready. "
        f"({total_inserted} records in {elapsed:.1f}s)"
    )
    logger.info(f"    Entities: {target.num_entities}")
    logger.info(f"    Fields:   {[f.name for f in target.schema.fields]}")

    if total_skipped > 0:
        logger.warning(f"⚠️  {total_skipped} rows failed. Error log: {error_file_name}")
    else:
        logger.info("✅  No errors during duplication.")

    # Clean up empty error file
    has_errors = (
        os.path.exists(error_file_path) and os.path.getsize(error_file_path) > 0
    )

    return {
        "target_collection": target_name,
        "total_inserted": total_inserted,
        "total_skipped": total_skipped,
        "elapsed_seconds": round(elapsed, 2),
        "fields": [f.name for f in target.schema.fields],
        "error_file": error_file_name if has_errors else None,
    }


def retry_failed_rows(
    source_name: str,
    target_name: str,
    error_file_name: str,
    text_field: str = "text",
    batch_size: int = 100,
):
    """
    Re-insert failed rows from an error log file into the target collection.

    Reads the error TXT file line by line, parses each JSON line to get
    the original row data, sanitizes it, and attempts to re-insert into
    the target collection. Rows that still fail are written to a new
    error file.

    Args:
        source_name: Source collection name (for schema reference)
        target_name: Target collection to re-insert into
        error_file_name: Filename of the error TXT (in ERROR_LOG_DIR)
        text_field: VARCHAR field used for BM25 generation
        batch_size: Number of records to re-insert per batch

    Returns:
        dict with total_retried, total_succeeded, total_still_failed,
        new_error_file (if any rows still fail)
    """
    error_file_path = os.path.join(ERROR_LOG_DIR, error_file_name)
    if not os.path.exists(error_file_path):
        raise FileNotFoundError(f"Error file not found: {error_file_name}")

    # ── Load rows from error file ──
    failed_rows = []
    with open(error_file_path, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                failed_rows.append(entry)
            except json.JSONDecodeError as e:
                logger.warning(f"⚠️  Skipping malformed line #{line_num}: {e}")

    if not failed_rows:
        return {
            "total_retried": 0,
            "total_succeeded": 0,
            "total_still_failed": 0,
            "new_error_file": None,
            "message": "No failed rows found in error file.",
        }

    logger.info(f"🔄  Retrying {len(failed_rows)} failed rows from '{error_file_name}'")

    # ── Connect and load target collection ──
    source = Collection(source_name)
    source.load()
    target = Collection(target_name)
    target.load()

    schema_field_types = {f.name: f.dtype for f in source.schema.fields}
    # Build field list from target schema, excluding BM25 auto-generated fields
    target_auto_generated = set()
    for func in target.schema.functions:
        for out_name in func.output_field_names:
            target_auto_generated.add(out_name)
    # Also exclude PK field when auto_id=True (Milvus generates it)
    if target.schema.auto_id:
        pk_name = next((f.name for f in target.schema.fields if f.is_primary), None)
        if pk_name:
            target_auto_generated.add(pk_name)
    source_field_set = {f.name for f in source.schema.fields}
    field_names = [
        f.name
        for f in target.schema.fields
        if f.name not in target_auto_generated and f.name in source_field_set
    ]
    pk_field = next((f.name for f in source.schema.fields if f.is_primary), None)

    # ── Prepare new error file for rows that still fail ──
    retry_error_file_name = f"retry_{error_file_name}"
    retry_error_file_path = os.path.join(ERROR_LOG_DIR, retry_error_file_name)

    total_succeeded = 0
    total_still_failed = 0

    # ── Process each failed row ──
    for entry in failed_rows:
        row = entry.get("row", {})
        pk_value = entry.get("pk", "unknown")

        # Sanitize: convert list/dict values to JSON for VARCHAR fields
        clean_row = {}
        for field in field_names:
            val = row.get(field)
            if val is None:
                continue
            if schema_field_types.get(field) == DataType.VARCHAR and isinstance(
                val, (list, dict)
            ):
                clean_row[field] = json.dumps(val, ensure_ascii=False)
            else:
                clean_row[field] = val

        try:
            # Use column-based insert to avoid pymilvus adding implicit $meta column
            single_col = [[clean_row.get(field)] for field in field_names]
            target.insert(single_col)
            total_succeeded += 1
            logger.info(f"   ✅ Retried row (pk={pk_value}) — success")
        except Exception as e:
            total_still_failed += 1
            logger.error(f"   ❌ Retried row (pk={pk_value}) — still failed: {e}")
            _write_error_line(retry_error_file_path, pk_value, row, str(e))

    # ── Flush target ──
    target.flush()

    has_new_errors = (
        os.path.exists(retry_error_file_path)
        and os.path.getsize(retry_error_file_path) > 0
    )

    logger.info(
        f"\n🔄  Retry complete: {total_succeeded} succeeded, "
        f"{total_still_failed} still failed."
    )

    return {
        "total_retried": len(failed_rows),
        "total_succeeded": total_succeeded,
        "total_still_failed": total_still_failed,
        "new_error_file": retry_error_file_name if has_new_errors else None,
        "message": (
            f"Retried {len(failed_rows)} rows: "
            f"{total_succeeded} succeeded, {total_still_failed} still failed."
        ),
    }
