apiVersion: v1
kind: ServiceAccount
metadata:
  name: opti-moteur-sa
  namespace: moteur-recherche
  labels:
    app.kubernetes.io/name: opti-moteur-recherche
    app.kubernetes.io/managed-by: manifest
    environment: prod
    owner: devsecops
    cost-center: ia-rag
    app: opti-moteur-recherche
