apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-milvus-prod
  namespace: moteur-recherche
  labels:
    app.kubernetes.io/managed-by: manifest
    environment: prod
spec:
  podSelector:
    matchLabels:
      app: opti-moteur-recherche
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: milvus-prod
      ports:
        - protocol: TCP
          port: 19530   # gRPC API Milvus (svc milvus-prod, confirme discovery 2026-04-28)
        - protocol: TCP
          port: 9091    # mgmt (svc milvus-prod-mgmt)
