apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-vm-gpu-embedding
  namespace: moteur-recherche
  labels:
    app.kubernetes.io/managed-by: manifest
    environment: prod
spec:
  podSelector:
    matchLabels:
      app: opti-moteur-recherche
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.11.0.2/32   # vm-embedding-g2-std-24-use (us-east4-c) — discovery 2026-04-28
      ports:
        - protocol: TCP
          port: 8555    # api-embedding-service
