
name: 'Build and Deploy devis database services'

on:
  # push:
  #   branches:
  #     - main
  #     - preprod
  #     - develop
  #   paths:
  #     - 'apps-services/embedding-service/**'
  # pull_request:
  #   branches:
  #     - main
  #     - develop
  #     - features/poc
  #     - features/embedding-service
  #   paths:
  #     - 'apps-services/embedding-service/**'
  # workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read

env:
  PROJECT_ID: 'hellopro-rag-project' # TODO: a ajouter dans les variables d'environnement du repo
  REGION: 'europe-west1' # TODO: a ajouter dans les variables d'environnement du repo
  SERVICE: 'devis-database-dev' # TODO: a ajuster selon le services
  VARIABLES: ${{ secrets.PROD_ENV }}
  SERVICE_NAME: 'di-database-qdrant-service' # 'embedding-service' # TODO: a ajuster selon le service

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    defaults:
      run:
        working-directory: apps-microservices/${{ env.SERVICE_NAME }}   # TODO: a ajuster selon le services

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download CI artifacts
        uses: actions/download-artifact@v4
        with:
          name: devis-database-ci-artifacts
          path: ./dist
      
      - name: Copie fichier env
        run: echo '${{ secret.ENV_FILE_EMBEDDING }}' > .env

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_DEV }}'

      - name: Set Google Cloud Project
        run:  gcloud config set project ${{ secrets.GCP_PROJECT_ID_DEV }}


      - name: Authenticate to Google Cloud
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and Push Container'
        run: |-
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/hellopro/${{ env.SERVICE }}-${{ github.sha }}" .
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/hellopro/${{ env.SERVICE }}"
      - name: 'Deploy to Cloud Run'

        # END - Docker auth and build

        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          flags: '--ingress internal-and-cloud-load-balancing --allow-unauthenticated  --vpc-connector=vpc-access-connector   --memory 16Gi --cpu 8'

          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/hellopro/${{ env.SERVICE }}-${{ github.sha }}'
      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |2-

          echo ${{ steps.deploy.outputs.url }}