# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI SERVICE API INGESTION

on:
  # push:
  #   branches: [ "main" , "features/api-ingestion" ]
  # pull_request:
  #   branches: [ "main" , "develop" ]
  # workflow_dispatch:
  workflow_call:
    
env:
  SERVICE_NAME: 'api-ingestion'

jobs:
  test:
    runs-on: ubuntu-latest
    
    # defaults:
    #   run:
    #     working-directory: apps-services/api-ingestion/   # TODO: a ajuster selon le services

    steps:
    - name: Get the code
      uses: actions/checkout@v4
      
    # - name: Cache Python packages
    #   uses: actions/cache@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        cd apps-microservices/${{ env.SERVICE_NAME }}
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        cd apps-microservices/api-ingestion
        source .venv/bin/activate
        pytest tests/ --maxfail=3 --disable-warnings -v
    
    # Optionnel : publier des artefacts (build, rapports, etc.)
    - name: Package artifact
      run: |
        mkdir -p dist && echo "ok" > dist/ci-ok.txt
    - uses: actions/upload-artifact@v4
      with:
        name: api-ingestion-ci-artifacts
        path: dist/