name: Pipeline Orchestrator Categories Database
on:
  push:
    branches:
      - main
      - preprod
      - develop
    paths:
      - 'apps-microservices/categories-database-qdrant-service/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - preprod
      - develop
      - features/poc
    paths:
      - 'apps-microservices/categories-database-qdrant-service/**'
      - '.github/workflows/**'
  workflow_dispatch: {}


env:
  SERVICE_NAME: 'services_categories_database_qdrant' # 'website-database-qdrant-service' # TODO: a ajuster selon le service

concurrency:
  group: ${{ env.SERVICE_NAME }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  call-ci-service:
    name: Call CI Services
    uses: ./.github/workflows/ci_${{ env.SERVICE_NAME }}.yml

  call-cd-service:
    name: Call CD Build and Push Services Individually
    needs: [call-ci-service]          # CD ne s’exécute que si CI a réussi
    if: ${{ github.event_name == 'push' && contains(fromJSON('["refs/heads/main","refs/heads/preprod","refs/heads/develop"]'), github.ref) }}
    uses: ./.github/workflows/cd_build_push_${{ env.SERVICE_NAME }}.yml